### ISSUE TITLE
Error: base64@1.0.1 install: `node-waf configure build`

### ISSUE THREAD

**Issue by rjack** [pkrumins/node-base64#5]
Hello,

got an error when I install base64 1.0.1 via npm.

<pre>npm info install base64@1.0.1
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr/local/jack 
'configure' finished successfully (0.096s)
Waf: Entering directory `/usr/local/jack/lib/node/.npm/base64/1.0.1/package/build'
[1/2] cxx: base64.cc -> build/default/base64_1.o
../base64.cc: In function ‘v8::Handle<v8::Value> base64_encode_binding(const v8::Arguments&)’:
../base64.cc:132: error: ‘class node::Buffer’ has no member named ‘data’
../base64.cc:132: error: ‘class node::Buffer’ has no member named ‘length’
../base64.cc: In function ‘v8::Handle<v8::Value> base64_decode_binding(const v8::Arguments&)’:
../base64.cc:150: error: ‘class node::Buffer’ has no member named ‘data’
../base64.cc:150: error: ‘class node::Buffer’ has no member named ‘length’
Waf: Leaving directory `/usr/local/jack/lib/node/.npm/base64/1.0.1/package/build'
Build failed:  -> task failed (err #1): 
    {task: cxx base64.cc -> base64_1.o}
npm info base64@1.0.1 Failed to exec install script
npm ERR! install failed Error: base64@1.0.1 install: `node-waf configure build`
npm ERR! install failed `sh` failed with 1
npm ERR! install failed     at ChildProcess.<anonymous> (/usr/local/jack/lib/node/.npm/npm/0.2.14-1/package/lib/utils/exec.js:25:18)
npm ERR! install failed     at ChildProcess.emit (events.js:34:17)
npm ERR! install failed     at ChildProcess.onexit (child_process.js:164:12)</pre>

Cheers,
Giacomo

**Comment by rjack** [comment]
Additional infos:

<pre>npm 0.2.14-1
node v0.3.3</pre>

**Comment by neverender** [comment]
I got this error too

**Comment by tacoman667** [comment]
As did I.  Can't install zombie.js because of it.

**Comment by felipero** [comment]
Me too:
npm: 0.2.5
node: 0.3.4

**Comment by felipero** [comment]
By the way, why is this closed?

**Comment by pkrumins** [comment]
hey guys, i was not aware of this issue, i just upgraded node-base64 to work on 0.3.x (but it no longer works on node 0.2.x).

**Comment by pkrumins** [comment]
hey guys, i was not aware of this issue, i just upgraded node-base64 to work on 0.3.x (but it no longer works on node 0.2.x).

**Comment by clickwhit** [comment]
I have this issue still.

**Comment by cly** [comment]
this is a problem for me as well.. very frustrating. and also trying to use zombie.js

**Comment by clickwhit** [comment]
Found a temporary solution here:
https://gist.github.com/765894

**Comment by pkrumins** [comment]
I am happy you guys have a temporary solution.
